services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: quan
      POSTGRES_DB: food_delivery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_java:/var/lib/postgresql/data
  java:
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: quan
      DB_NAME: food_delivery
    depends_on:
      - postgres
    ports:
      - "8080:8080"
volumes:
  postgres_data_java: